-- ============================================================
-- SP_BUILD_FACT_RIDE_JC.sql
-- Identical logic sourced from STAGING_JC.TRIPS_ALL
-- ============================================================
 
CREATE OR REPLACE PROCEDURE CITIBIKE_SYSTEM_DATA.INT_UDM_JC.SP_BUILD_FACT_RIDE_JC(
    P_TRUNCATE_FIRST BOOLEAN DEFAULT FALSE
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    rows_inserted INTEGER DEFAULT 0;
BEGIN
 
    IF (P_TRUNCATE_FIRST) THEN
        TRUNCATE TABLE CITIBIKE_SYSTEM_DATA.INT_UDM_JC.FACT_RIDE;
    END IF;
 
    INSERT INTO CITIBIKE_SYSTEM_DATA.INT_UDM_JC.FACT_RIDE (
        TRIP_SK_STAGING,
        RIDE_ID,
        START_STATION_SK,
        END_STATION_SK,
        START_DATE_SK,
        END_DATE_SK,
        STARTED_AT,
        ENDED_AT,
        TRIP_DURATION_SEC,
        TRIP_DURATION_MIN,
        START_HOUR,
        RIDEABLE_TYPE,
        BIKEID,
        MEMBER_CASUAL,
        BIRTH_YEAR,
        GENDER,
        AGE_AT_RIDE,
        AGE_BUCKET,
        SOURCE_SCHEMA,
        _SOURCE_FILE,
        _SOURCE_ROW_NUMBER,
        _LOADED_AT
    )
    SELECT
        SRC.TRIP_SK,
        SRC.RIDE_ID,
        SS.STATION_SK,
        ES.STATION_SK,
        TO_NUMBER(TO_CHAR(SRC.STARTED_AT::DATE, 'YYYYMMDD')),
        TO_NUMBER(TO_CHAR(SRC.ENDED_AT::DATE,   'YYYYMMDD')),
        SRC.STARTED_AT,
        SRC.ENDED_AT,
        SRC.TRIP_DURATION,
        ROUND(SRC.TRIP_DURATION / 60.0, 2),
        HOUR(SRC.STARTED_AT),
        LOWER(TRIM(SRC.RIDEABLE_TYPE)),
        SRC.BIKEID,
        COALESCE(LOWER(TRIM(SRC.MEMBER_CASUAL)), 'unknown')  AS MEMBER_CASUAL,
        SRC.BIRTH_YEAR,
        SRC.GENDER,
        CASE
            WHEN SRC.BIRTH_YEAR BETWEEN 1900 AND 2010
            THEN YEAR(SRC.STARTED_AT) - SRC.BIRTH_YEAR
            ELSE NULL
        END,
        CASE
            WHEN SRC.BIRTH_YEAR IS NULL                         THEN NULL
            WHEN YEAR(SRC.STARTED_AT) - SRC.BIRTH_YEAR < 18    THEN '<18'
            WHEN YEAR(SRC.STARTED_AT) - SRC.BIRTH_YEAR < 25    THEN '18-24'
            WHEN YEAR(SRC.STARTED_AT) - SRC.BIRTH_YEAR < 35    THEN '25-34'
            WHEN YEAR(SRC.STARTED_AT) - SRC.BIRTH_YEAR < 45    THEN '35-44'
            WHEN YEAR(SRC.STARTED_AT) - SRC.BIRTH_YEAR < 55    THEN '45-54'
            WHEN YEAR(SRC.STARTED_AT) - SRC.BIRTH_YEAR < 65    THEN '55-64'
            ELSE                                                     '65+'
        END,
        CASE
            WHEN SPLIT_PART(SRC._SOURCE_FILE, '_', 2) = 'dc497b4333c4' THEN 'MODERN'
            WHEN SPLIT_PART(SRC._SOURCE_FILE, '_', 2) = '473144999085' THEN 'LEGACY_V1'
            ELSE 'LEGACY_V2'
        END AS SOURCE_SCHEMA,
        SRC._SOURCE_FILE,
        SRC._SOURCE_ROW_NUMBER,
        CURRENT_TIMESTAMP()
    FROM CITIBIKE_SYSTEM_DATA.STAGING_JC.TRIPS_ALL SRC
    LEFT JOIN CITIBIKE_SYSTEM_DATA.INT_UDM_JC.DIM_STATION SS
        ON SS.STATION_NAME = TRIM(UPPER(SRC.START_STATION_NAME))
    LEFT JOIN CITIBIKE_SYSTEM_DATA.INT_UDM_JC.DIM_STATION ES
        ON ES.STATION_NAME = TRIM(UPPER(SRC.END_STATION_NAME))
    WHERE NOT EXISTS (
        SELECT 1
        FROM CITIBIKE_SYSTEM_DATA.INT_UDM_JC.FACT_RIDE TGT
        WHERE TGT._SOURCE_FILE       = SRC._SOURCE_FILE
          AND TGT._SOURCE_ROW_NUMBER = SRC._SOURCE_ROW_NUMBER
    )
    AND SRC.TRIP_DURATION BETWEEN 60 AND 86400
    AND SRC.STARTED_AT::DATE BETWEEN '2013-01-01' AND '2030-12-31';
 
    rows_inserted := SQLROWCOUNT;
    RETURN 'SP_BUILD_FACT_RIDE_JC: inserted ' || rows_inserted || ' rows into INT_UDM_JC.FACT_RIDE';
 
END;
$$;