-- -----------------------------------------------------------
-- V_TABLE_ROW_COUNTS
-- Cross-check: rows loaded according to the log vs actual table counts.
-- Discrepancy means a file was counted as SUCCESS but data is missing.
-- -----------------------------------------------------------
CREATE OR REPLACE VIEW CITIBIKE_SYSTEM_DATA.LOGGING.V_TABLE_ROW_COUNTS AS
WITH log_counts AS (
    SELECT
        SF_SCHEMA,
        SF_TABLE,
        SUM(ROWS_LOADED) AS LOG_ROWS_LOADED,
        COUNT(*)         AS FILES_LOADED
    FROM CITIBIKE_SYSTEM_DATA.LOGGING.INGEST_LOG
    WHERE STATUS = 'SUCCESS'
    GROUP BY SF_SCHEMA, SF_TABLE
)
SELECT
    lc.SF_SCHEMA,
    lc.SF_TABLE,
    lc.LOG_ROWS_LOADED,
    lc.FILES_LOADED,
    -- Actual table counts (union all six tables, filter by schema+table name)
    t.ACTUAL_ROW_COUNT,
    (lc.LOG_ROWS_LOADED - t.ACTUAL_ROW_COUNT) AS DISCREPANCY
FROM log_counts lc
JOIN (
    -- STAGING_NYC
    SELECT 'STAGING_NYC' AS SF_SCHEMA, 'TRIPS_LEGACY_V1' AS SF_TABLE, COUNT(*) AS ACTUAL_ROW_COUNT FROM CITIBIKE_SYSTEM_DATA.STAGING_NYC.TRIPS_LEGACY_V1
    UNION ALL
    SELECT 'STAGING_NYC', 'TRIPS_LEGACY_V2', COUNT(*) FROM CITIBIKE_SYSTEM_DATA.STAGING_NYC.TRIPS_LEGACY_V2
    UNION ALL
    SELECT 'STAGING_NYC', 'TRIPS_MODERN',    COUNT(*) FROM CITIBIKE_SYSTEM_DATA.STAGING_NYC.TRIPS_MODERN
    -- STAGING_JC
    UNION ALL
    SELECT 'STAGING_JC', 'TRIPS_LEGACY_V1', COUNT(*) FROM CITIBIKE_SYSTEM_DATA.STAGING_JC.TRIPS_LEGACY_V1
    UNION ALL
    SELECT 'STAGING_JC', 'TRIPS_LEGACY_V2', COUNT(*) FROM CITIBIKE_SYSTEM_DATA.STAGING_JC.TRIPS_LEGACY_V2
    UNION ALL
    SELECT 'STAGING_JC', 'TRIPS_MODERN',    COUNT(*) FROM CITIBIKE_SYSTEM_DATA.STAGING_JC.TRIPS_MODERN
) t ON t.SF_SCHEMA = lc.SF_SCHEMA AND t.SF_TABLE = lc.SF_TABLE
ORDER BY lc.SF_SCHEMA, lc.SF_TABLE;