-- -----------------------------------------------------------
-- SP_LOAD_TRIPS_LEGACY_V2
-- Merge TRIPS_LEGACY_V2 → TRIPS_ALL (NYC). Idempotent on source file + row.
-- -----------------------------------------------------------

CREATE OR REPLACE PROCEDURE CITIBIKE_SYSTEM_DATA.STAGING_NYC.SP_LOAD_TRIPS_LEGACY_V2()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    rows_inserted INTEGER DEFAULT 0;
BEGIN
    INSERT INTO CITIBIKE_SYSTEM_DATA.STAGING_NYC.TRIPS_ALL (
        RIDE_ID,
        RIDEABLE_TYPE,
        BIKEID,
        STARTED_AT,
        ENDED_AT,
        TRIP_DURATION,
        START_STATION_NAME,
        START_STATION_ID,
        END_STATION_NAME,
        END_STATION_ID,
        START_LAT,
        START_LNG,
        END_LAT,
        END_LNG,
        MEMBER_CASUAL,
        BIRTH_YEAR,
        GENDER,
        _SOURCE_FILE,
        _SOURCE_ROW_NUMBER,
        _LOADED_AT,
        _LOADED_AT_TBL
    )
    SELECT
        NULL::VARCHAR AS RIDE_ID,
        NULL::VARCHAR AS RIDEABLE_TYPE,
        SRC.BIKE_ID AS BIKEID,
        SRC.START_TIME AS STARTED_AT,
        SRC.STOP_TIME AS ENDED_AT,
        SRC.TRIP_DURATION,
        SRC.START_STATION_NAME,
        TO_VARCHAR(SRC.START_STATION_ID) AS START_STATION_ID,
        SRC.END_STATION_NAME,
        TO_VARCHAR(SRC.END_STATION_ID) AS END_STATION_ID,
        SRC.START_STATION_LATITUDE AS START_LAT,
        SRC.START_STATION_LONGITUDE AS START_LNG,
        SRC.END_STATION_LATITUDE AS END_LAT,
        SRC.END_STATION_LONGITUDE AS END_LNG,
        CASE
            WHEN LOWER(SRC.USER_TYPE) = 'subscriber' THEN 'member'
            WHEN LOWER(SRC.USER_TYPE) = 'customer' THEN 'casual'
            ELSE LOWER(SRC.USER_TYPE)
        END AS MEMBER_CASUAL,
        SRC.BIRTH_YEAR,
        SRC.GENDER,
        SRC._SOURCE_FILE,
        SRC._SOURCE_ROW_NUMBER,
        SRC._LOADED_AT,
        CURRENT_TIMESTAMP() AS _LOADED_AT_TBL
    FROM CITIBIKE_SYSTEM_DATA.STAGING_NYC.TRIPS_LEGACY_V2 SRC
    WHERE NOT EXISTS (
        SELECT 1
        FROM CITIBIKE_SYSTEM_DATA.STAGING_NYC.TRIPS_ALL TGT
        WHERE TGT._SOURCE_FILE = SRC._SOURCE_FILE
          AND TGT._SOURCE_ROW_NUMBER = SRC._SOURCE_ROW_NUMBER
    );

    rows_inserted := SQLROWCOUNT;
    RETURN 'SP_LOAD_TRIPS_LEGACY_V2 (NYC): inserted ' || rows_inserted || ' rows into TRIPS_ALL';
END;
$$;
