CREATE TABLE IF NOT EXISTS CITIBIKE_SYSTEM_DATA.INT_UDM_NYC.DIM_DATES (
    DATE_SK INT NOT NULL PRIMARY KEY COMMENT 'Surrogate key in YYYYMMDD integer format e.g. 20130601',
    FULL_DATE DATE NOT NULL UNIQUE COMMENT 'Calendar date',
    -- Calendar breakdowns
    DAY_OF_WEEK_NUM TINYINT NOT NULL COMMENT '1=Monday … 7=Sunday (ISO)',
    DAY_OF_WEEK_NAME VARCHAR(10) NOT NULL COMMENT 'Monday, Tuesday …',
    DAY_OF_WEEK_SHORT VARCHAR(3) NOT NULL COMMENT 'Mon, Tue …',
    IS_WEEKEND BOOLEAN NOT NULL COMMENT 'TRUE if Saturday or Sunday',
    DAY_OF_MONTH TINYINT NOT NULL,
    DAY_OF_YEAR SMALLINT NOT NULL,
    WEEK_OF_YEAR TINYINT NOT NULL COMMENT 'ISO week number 1-53',
    MONTH_NUM TINYINT NOT NULL COMMENT '1-12',
    MONTH_NAME VARCHAR(10) NOT NULL COMMENT 'January, February …',
    MONTH_SHORT VARCHAR(3) NOT NULL COMMENT 'Jan, Feb …',
    QUARTER_NUM TINYINT NOT NULL COMMENT '1-4',
    YEAR_NUM SMALLINT NOT NULL,
    YEAR_MONTH VARCHAR(7) NOT NULL COMMENT 'YYYY-MM e.g. 2013-06',
    -- Season (meteorological)
    SEASON VARCHAR(10)     NOT NULL COMMENT 'Spring | Summer | Autumn | Winter',
    -- Holiday flags
    IS_HOLIDAY BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'TRUE if US federal or NY state public holiday',
    HOLIDAY_NAME VARCHAR(100) COMMENT 'Holiday name if IS_HOLIDAY = TRUE, else NULL',
    -- Useful date references
    FIRST_DAY_OF_MONTH DATE NOT NULL,
    LAST_DAY_OF_MONTH DATE NOT NULL,
    FIRST_DAY_OF_YEAR DATE NOT NULL,
    LAST_DAY_OF_YEAR DATE NOT NULL
)
COMMENT = 'Date dimension spine covering 2013-01-01 to 2030-12-31. Populated by SP_BUILD_DIM_DATES.';
