-- Failed files with their error messages
SELECT
    OUTPUT_FILE, ATTEMPT, ERROR_MESSAGE, ENDED_AT_UTC
FROM CITIBIKE_SYSTEM_DATA.LOGGING.V_LATEST_INGEST_STATUS
WHERE STATUS = 'FAILED'
ORDER BY ENDED_AT_UTC DESC;