-- Any file with >0 errors (partial loads)
SELECT
    OUTPUT_FILE, SF_TABLE, ROWS_LOADED, ERRORS_SEEN, COPY_STATUS_RAW
FROM CITIBIKE_SYSTEM_DATA.LOGGING.INGEST_LOG
WHERE STATUS  = 'SUCCESS'
  AND ERRORS_SEEN > 0
ORDER BY ERRORS_SEEN DESC;