-- Run status overview
SELECT
    STATUS,
    REGION,
    SF_TABLE,
    COUNT(*)         AS FILE_COUNT,
    SUM(ROWS_LOADED) AS TOTAL_ROWS,
    SUM(ERRORS_SEEN) AS TOTAL_ERRORS
FROM CITIBIKE_SYSTEM_DATA.LOGGING.INGEST_LOG
GROUP BY STATUS, REGION, SF_TABLE
ORDER BY REGION, SF_TABLE, STATUS;